service: scaleway-secrets
configValidationMode: off
provider:
  name: scaleway
  runtime: python310 # Available python runtimes are listed in documentation
  # Global Environment variables - used in every functions
  env:
    env_notSecretA: notSecret
  # Global Secret Environment variables - used in every functions
  secret:
    env_secretA: valueA
    env_secretB: "value with special characters ^:;"
    env_secretC: ${ENV_SECRETC} # reference to a local env var ENV_SECRETC, must be set

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'

functions:
  first:
    handler: handler.handle
    # Local environment variables - used only in given function
    env:
      env_notSecret1: notSecret1
    # Local secret environment variables - used only in given function
    secret:
      env_secret1: value1
      env_secret2: "other value with special characters ^:;"
      env_secret3: ${ENV_SECRET3} # reference to a local env var ENV_SECRET3, must be set
