service: container-event-example
configValidationMode: off

provider:
  name: scaleway

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"

custom:
  containers:
    first:
      directory: container
      events:
        - schedule:
            rate: "1 * * * *"
            input:
              field-a: "some value"
              field-b: 1234
