service: scaleway-container
configValidationMode: off
provider:
  name: scaleway
  # Global Environment variables - used in every functions
  env:
    test: test

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'

custom:
  containers:
    first:
      directory: my-container
      events:
        - schedule:
            rate: '1 * * * *'
            input:
              myInput: myValue
              mySecondInput: 1
      # minScale: 1
      # memoryLimit: 256
      # maxScale: 2
      # maxConcurrency: 50
      # timeout: 20000
      # Local environment variables - used only in given function
      env:
        local: local
