service: scaleway-rust
configValidationMode: off
provider:
  name: scaleway
  runtime: rust179 # Available rust runtimes are listed in documentation
  # Global Environment variables - used in every functions
  env:
    test: test

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"

functions:
  first:
    # handler is just the name of the exported handler function
    handler: my_handler
    # description: ""
    # Local environment variables - used only in given function
    env:
      local: local
