service: scaleway-rust
configValidationMode: off
provider:
  name: scaleway
  runtime: rust165 # Available go runtimes are listed in documentation
  # Global Environment variables - used in every functions
  env:
    test: test

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'

functions:
  first:
    # handler is just the name of the exported handler function
    handler: MyHandler
    # description: ""
    # Local environment variables - used only in given function
    env:
      local: local
